### ISSUE TITLE
Class Cast Exception in the facebook_url case statement of readStates method

### ISSUE THREAD

**Issue by LukeTownsend10** [kmorcha18/CSC346group4#3]
The facebook_url case statement in the readStates method return the error code at the bottom of this comment. It's basically saying that it can't save the information between the facebook_url tags because it is an end tag. This case statement isn't any different than the others. If you comment out just that case statement the program will run as intended. If someone could help me figure out where the logic is incorrect that would be great.

Exception in thread "main" java.lang.ClassCastException: class com.sun.xml.internal.stream.events.EndElementEvent cannot be cast to class javax.xml.stream.events.Characters (com.sun.xml.internal.stream.events.EndElementEvent and javax.xml.stream.events.Characters are in module java.xml of loader 'bootstrap')
	at java.xml/com.sun.xml.internal.stream.events.DummyEvent.asCharacters(DummyEvent.java:115)
	at App.readStates(App.java:193)
	at App.main(App.java:24)

**Comment by LukeTownsend10** [comment]
Error was fixed by creating a check for no character data between the tags. Washington had no data for it's facebook url, causing the next call of the iterator to reach an end element instead of a character element.
